---
version: 2

updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
      time: '22:00'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '22:00'

  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
      time: '22:00'
